name: Auth

on:
  workflow_dispatch:
  push:

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    # environment: test-environment

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
      TEST: ${{ secrets.TEST }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Print TEST'
        run: echo ${{ env.TEST }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
          token_format: access_token

      - name: Login to GAR
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          # ドキュメント通り
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ vars.REGION }}-docker.pkg.dev'
